name: film_oasis
description: "Movie App"

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Managment
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # Service
  dio: ^5.7.0

  # Private Key
  flutter_dotenv: ^5.1.0

  # Core
  intl: ^0.19.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7

  # Navigate
  auto_route: ^9.2.2

  # Cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Animation
  lottie: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true  
  ios: true
  image_path: "assets/png/icon.png"
  adaptive_icon_background: "#000000FF"  
  adaptive_icon_foreground: "assets/png/icon.png"  

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/json/
    - assets/png/



  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Mulish-Bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf    

