name: film_oasis
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Managment
  flutter_riverpod: ^2.5.1

  # Service
  dio: ^5.7.0

  # Private Key
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^6.0.0

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Mulish-Bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
